export default [
  {
    id: 533751988,
    node_id: 'R_kgDOH9BotA',
    name: '-test-task-filter',
    full_name: 'Moskvin23/-test-task-filter',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/-test-task-filter',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/-test-task-filter',
    forks_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/-test-task-filter/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/hooks',
    issue_events_url:
      'https://api.github.com/repos/Moskvin23/-test-task-filter/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/events',
    assignees_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/stargazers',
    contributors_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/subscribers',
    subscription_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Moskvin23/-test-task-filter/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/merges',
    archive_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/-test-task-filter/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/-test-task-filter/deployments',
    created_at: '2022-09-07T12:17:37Z',
    updated_at: '2022-09-07T12:21:57Z',
    pushed_at: '2022-09-07T12:21:52Z',
    git_url: 'git://github.com/Moskvin23/-test-task-filter.git',
    ssh_url: 'git@github.com:Moskvin23/-test-task-filter.git',
    clone_url: 'https://github.com/Moskvin23/-test-task-filter.git',
    svn_url: 'https://github.com/Moskvin23/-test-task-filter',
    homepage: null,
    size: 307,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
  },
  {
    id: 369772991,
    node_id: 'MDEwOlJlcG9zaXRvcnkzNjk3NzI5OTE=',
    name: 'Analog-Clock',
    full_name: 'Moskvin23/Analog-Clock',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/Analog-Clock',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/Analog-Clock',
    forks_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/Analog-Clock/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/hooks',
    issue_events_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/events',
    assignees_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/stargazers',
    contributors_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/subscribers',
    subscription_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Moskvin23/Analog-Clock/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/merges',
    archive_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/Analog-Clock/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/Analog-Clock/deployments',
    created_at: '2021-05-22T09:57:32Z',
    updated_at: '2021-05-30T17:54:37Z',
    pushed_at: '2021-05-30T17:54:35Z',
    git_url: 'git://github.com/Moskvin23/Analog-Clock.git',
    ssh_url: 'git@github.com:Moskvin23/Analog-Clock.git',
    clone_url: 'https://github.com/Moskvin23/Analog-Clock.git',
    svn_url: 'https://github.com/Moskvin23/Analog-Clock',
    homepage: null,
    size: 4,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'CSS',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
  },
  {
    id: 372266160,
    node_id: 'MDEwOlJlcG9zaXRvcnkzNzIyNjYxNjA=',
    name: 'bmw-x6',
    full_name: 'Moskvin23/bmw-x6',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/bmw-x6',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/bmw-x6',
    forks_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/hooks',
    issue_events_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/events',
    assignees_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/stargazers',
    contributors_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/subscribers',
    subscription_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/merges',
    archive_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/bmw-x6/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/bmw-x6/deployments',
    created_at: '2021-05-30T16:40:25Z',
    updated_at: '2021-05-30T17:08:56Z',
    pushed_at: '2021-05-30T17:08:54Z',
    git_url: 'git://github.com/Moskvin23/bmw-x6.git',
    ssh_url: 'git@github.com:Moskvin23/bmw-x6.git',
    clone_url: 'https://github.com/Moskvin23/bmw-x6.git',
    svn_url: 'https://github.com/Moskvin23/bmw-x6',
    homepage: null,
    size: 5048,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Sass',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
  },
  {
    id: 369774228,
    node_id: 'MDEwOlJlcG9zaXRvcnkzNjk3NzQyMjg=',
    name: 'Calculator-with-dark-theme',
    full_name: 'Moskvin23/Calculator-with-dark-theme',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/Calculator-with-dark-theme',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme',
    forks_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/hooks',
    issue_events_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/events',
    assignees_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/assignees{/user}',
    branches_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/git/blobs{/sha}',
    git_tags_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/git/tags{/sha}',
    git_refs_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/git/trees{/sha}',
    statuses_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/stargazers',
    contributors_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/contributors',
    subscribers_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/subscribers',
    subscription_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/commits{/sha}',
    git_commits_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/git/commits{/sha}',
    comments_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/issues/comments{/number}',
    contents_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/contents/{+path}',
    compare_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/merges',
    archive_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/pulls{/number}',
    milestones_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/releases{/id}',
    deployments_url:
      'https://api.github.com/repos/Moskvin23/Calculator-with-dark-theme/deployments',
    created_at: '2021-05-22T10:04:03Z',
    updated_at: '2021-05-30T17:53:34Z',
    pushed_at: '2021-05-30T17:53:32Z',
    git_url: 'git://github.com/Moskvin23/Calculator-with-dark-theme.git',
    ssh_url: 'git@github.com:Moskvin23/Calculator-with-dark-theme.git',
    clone_url: 'https://github.com/Moskvin23/Calculator-with-dark-theme.git',
    svn_url: 'https://github.com/Moskvin23/Calculator-with-dark-theme',
    homepage: null,
    size: 5,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'CSS',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
  },
  {
    id: 429174451,
    node_id: 'R_kgDOGZSusw',
    name: 'chuck-norris-app-test-task-',
    full_name: 'Moskvin23/chuck-norris-app-test-task-',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/chuck-norris-app-test-task-',
    description: 'There is my first test task',
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-',
    forks_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/hooks',
    issue_events_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/events',
    assignees_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/assignees{/user}',
    branches_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/git/blobs{/sha}',
    git_tags_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/git/tags{/sha}',
    git_refs_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/git/trees{/sha}',
    statuses_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/stargazers',
    contributors_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/contributors',
    subscribers_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/subscribers',
    subscription_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/commits{/sha}',
    git_commits_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/git/commits{/sha}',
    comments_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/issues/comments{/number}',
    contents_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/contents/{+path}',
    compare_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/merges',
    archive_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/downloads',
    issues_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/pulls{/number}',
    milestones_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/labels{/name}',
    releases_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/releases{/id}',
    deployments_url:
      'https://api.github.com/repos/Moskvin23/chuck-norris-app-test-task-/deployments',
    created_at: '2021-11-17T19:27:28Z',
    updated_at: '2021-11-17T19:54:42Z',
    pushed_at: '2021-11-17T19:54:40Z',
    git_url: 'git://github.com/Moskvin23/chuck-norris-app-test-task-.git',
    ssh_url: 'git@github.com:Moskvin23/chuck-norris-app-test-task-.git',
    clone_url: 'https://github.com/Moskvin23/chuck-norris-app-test-task-.git',
    svn_url: 'https://github.com/Moskvin23/chuck-norris-app-test-task-',
    homepage: null,
    size: 767,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
  },
  {
    id: 353149721,
    node_id: 'MDEwOlJlcG9zaXRvcnkzNTMxNDk3MjE=',
    name: 'JS-583-Core',
    full_name: 'Moskvin23/JS-583-Core',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/JS-583-Core',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/JS-583-Core',
    forks_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/JS-583-Core/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/hooks',
    issue_events_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/events',
    assignees_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/stargazers',
    contributors_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/subscribers',
    subscription_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Moskvin23/JS-583-Core/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/merges',
    archive_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/JS-583-Core/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/JS-583-Core/deployments',
    created_at: '2021-03-30T21:46:24Z',
    updated_at: '2021-05-30T16:39:13Z',
    pushed_at: '2021-05-30T16:39:10Z',
    git_url: 'git://github.com/Moskvin23/JS-583-Core.git',
    ssh_url: 'git@github.com:Moskvin23/JS-583-Core.git',
    clone_url: 'https://github.com/Moskvin23/JS-583-Core.git',
    svn_url: 'https://github.com/Moskvin23/JS-583-Core',
    homepage: null,
    size: 27,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
  },
  {
    id: 372188905,
    node_id: 'MDEwOlJlcG9zaXRvcnkzNzIxODg5MDU=',
    name: 'Moskvin23',
    full_name: 'Moskvin23/Moskvin23',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/Moskvin23',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/Moskvin23',
    forks_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/Moskvin23/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/hooks',
    issue_events_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/events',
    assignees_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/stargazers',
    contributors_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/subscribers',
    subscription_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/merges',
    archive_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/Moskvin23/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/Moskvin23/deployments',
    created_at: '2021-05-30T10:49:38Z',
    updated_at: '2021-05-30T12:02:09Z',
    pushed_at: '2021-05-30T12:02:07Z',
    git_url: 'git://github.com/Moskvin23/Moskvin23.git',
    ssh_url: 'git@github.com:Moskvin23/Moskvin23.git',
    clone_url: 'https://github.com/Moskvin23/Moskvin23.git',
    svn_url: 'https://github.com/Moskvin23/Moskvin23',
    homepage: null,
    size: 6,
    stargazers_count: 0,
    watchers_count: 0,
    language: null,
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
  },
  {
    id: 372251001,
    node_id: 'MDEwOlJlcG9zaXRvcnkzNzIyNTEwMDE=',
    name: 'nike',
    full_name: 'Moskvin23/nike',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/nike',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/nike',
    forks_url: 'https://api.github.com/repos/Moskvin23/nike/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/nike/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/Moskvin23/nike/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/nike/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/nike/hooks',
    issue_events_url: 'https://api.github.com/repos/Moskvin23/nike/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/nike/events',
    assignees_url: 'https://api.github.com/repos/Moskvin23/nike/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Moskvin23/nike/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/nike/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/nike/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/nike/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/nike/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/nike/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/nike/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/nike/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/nike/stargazers',
    contributors_url: 'https://api.github.com/repos/Moskvin23/nike/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/nike/subscribers',
    subscription_url: 'https://api.github.com/repos/Moskvin23/nike/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/nike/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Moskvin23/nike/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Moskvin23/nike/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/Moskvin23/nike/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Moskvin23/nike/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Moskvin23/nike/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/nike/merges',
    archive_url: 'https://api.github.com/repos/Moskvin23/nike/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/nike/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/nike/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/nike/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Moskvin23/nike/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/nike/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/nike/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/nike/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/nike/deployments',
    created_at: '2021-05-30T15:32:36Z',
    updated_at: '2021-05-30T17:55:22Z',
    pushed_at: '2021-05-30T17:55:20Z',
    git_url: 'git://github.com/Moskvin23/nike.git',
    ssh_url: 'git@github.com:Moskvin23/nike.git',
    clone_url: 'https://github.com/Moskvin23/nike.git',
    svn_url: 'https://github.com/Moskvin23/nike',
    homepage: null,
    size: 1655,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'CSS',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
  },
  {
    id: 382868828,
    node_id: 'MDEwOlJlcG9zaXRvcnkzODI4Njg4Mjg=',
    name: 'react-smartphones',
    full_name: 'Moskvin23/react-smartphones',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/react-smartphones',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/react-smartphones',
    forks_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/react-smartphones/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/hooks',
    issue_events_url:
      'https://api.github.com/repos/Moskvin23/react-smartphones/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/events',
    assignees_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/stargazers',
    contributors_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/subscribers',
    subscription_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Moskvin23/react-smartphones/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/merges',
    archive_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/react-smartphones/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/react-smartphones/deployments',
    created_at: '2021-07-04T14:13:56Z',
    updated_at: '2021-07-16T12:43:53Z',
    pushed_at: '2021-07-16T12:43:50Z',
    git_url: 'git://github.com/Moskvin23/react-smartphones.git',
    ssh_url: 'git@github.com:Moskvin23/react-smartphones.git',
    clone_url: 'https://github.com/Moskvin23/react-smartphones.git',
    svn_url: 'https://github.com/Moskvin23/react-smartphones',
    homepage: null,
    size: 1801,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'SCSS',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
  },
  {
    id: 450197184,
    node_id: 'R_kgDOGtV2wA',
    name: 'react-test-task-app',
    full_name: 'Moskvin23/react-test-task-app',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/react-test-task-app',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/react-test-task-app',
    forks_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/react-test-task-app/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/hooks',
    issue_events_url:
      'https://api.github.com/repos/Moskvin23/react-test-task-app/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/events',
    assignees_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/stargazers',
    contributors_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/subscribers',
    subscription_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Moskvin23/react-test-task-app/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/contents/{+path}',
    compare_url:
      'https://api.github.com/repos/Moskvin23/react-test-task-app/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/merges',
    archive_url:
      'https://api.github.com/repos/Moskvin23/react-test-task-app/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/pulls{/number}',
    milestones_url:
      'https://api.github.com/repos/Moskvin23/react-test-task-app/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/react-test-task-app/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/react-test-task-app/deployments',
    created_at: '2022-01-20T17:40:06Z',
    updated_at: '2022-11-10T15:32:19Z',
    pushed_at: '2022-01-20T18:13:24Z',
    git_url: 'git://github.com/Moskvin23/react-test-task-app.git',
    ssh_url: 'git@github.com:Moskvin23/react-test-task-app.git',
    clone_url: 'https://github.com/Moskvin23/react-test-task-app.git',
    svn_url: 'https://github.com/Moskvin23/react-test-task-app',
    homepage: null,
    size: 299,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
  },
  {
    id: 451433041,
    node_id: 'R_kgDOGuhSUQ',
    name: 'react-test-task4',
    full_name: 'Moskvin23/react-test-task4',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/react-test-task4',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/react-test-task4',
    forks_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/react-test-task4/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/hooks',
    issue_events_url:
      'https://api.github.com/repos/Moskvin23/react-test-task4/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/events',
    assignees_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/stargazers',
    contributors_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/subscribers',
    subscription_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Moskvin23/react-test-task4/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/merges',
    archive_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/react-test-task4/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/react-test-task4/deployments',
    created_at: '2022-01-24T11:15:24Z',
    updated_at: '2022-01-24T15:32:45Z',
    pushed_at: '2022-01-24T15:32:41Z',
    git_url: 'git://github.com/Moskvin23/react-test-task4.git',
    ssh_url: 'git@github.com:Moskvin23/react-test-task4.git',
    clone_url: 'https://github.com/Moskvin23/react-test-task4.git',
    svn_url: 'https://github.com/Moskvin23/react-test-task4',
    homepage: null,
    size: 532,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
  },
  {
    id: 421745385,
    node_id: 'R_kgDOGSNS6Q',
    name: 'social-media',
    full_name: 'Moskvin23/social-media',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/social-media',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/social-media',
    forks_url: 'https://api.github.com/repos/Moskvin23/social-media/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/social-media/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/social-media/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/social-media/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/social-media/hooks',
    issue_events_url: 'https://api.github.com/repos/Moskvin23/social-media/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/social-media/events',
    assignees_url: 'https://api.github.com/repos/Moskvin23/social-media/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Moskvin23/social-media/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/social-media/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/social-media/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/social-media/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/social-media/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/social-media/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/social-media/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/social-media/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/social-media/stargazers',
    contributors_url: 'https://api.github.com/repos/Moskvin23/social-media/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/social-media/subscribers',
    subscription_url: 'https://api.github.com/repos/Moskvin23/social-media/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/social-media/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Moskvin23/social-media/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Moskvin23/social-media/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Moskvin23/social-media/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Moskvin23/social-media/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Moskvin23/social-media/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/social-media/merges',
    archive_url: 'https://api.github.com/repos/Moskvin23/social-media/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/social-media/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/social-media/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/social-media/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Moskvin23/social-media/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/social-media/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/social-media/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/social-media/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/social-media/deployments',
    created_at: '2021-10-27T08:56:21Z',
    updated_at: '2021-11-05T20:14:42Z',
    pushed_at: '2021-11-05T20:14:40Z',
    git_url: 'git://github.com/Moskvin23/social-media.git',
    ssh_url: 'git@github.com:Moskvin23/social-media.git',
    clone_url: 'https://github.com/Moskvin23/social-media.git',
    svn_url: 'https://github.com/Moskvin23/social-media',
    homepage: null,
    size: 426,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
  },
  {
    id: 596121227,
    node_id: 'R_kgDOI4gWiw',
    name: 'test-task',
    full_name: 'Moskvin23/test-task',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/test-task',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/test-task',
    forks_url: 'https://api.github.com/repos/Moskvin23/test-task/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/test-task/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/test-task/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/test-task/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/test-task/hooks',
    issue_events_url: 'https://api.github.com/repos/Moskvin23/test-task/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/test-task/events',
    assignees_url: 'https://api.github.com/repos/Moskvin23/test-task/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Moskvin23/test-task/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/test-task/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/test-task/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/test-task/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/test-task/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/test-task/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/test-task/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/test-task/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/test-task/stargazers',
    contributors_url: 'https://api.github.com/repos/Moskvin23/test-task/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/test-task/subscribers',
    subscription_url: 'https://api.github.com/repos/Moskvin23/test-task/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/test-task/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Moskvin23/test-task/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Moskvin23/test-task/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/Moskvin23/test-task/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Moskvin23/test-task/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Moskvin23/test-task/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/test-task/merges',
    archive_url: 'https://api.github.com/repos/Moskvin23/test-task/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/test-task/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/test-task/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/test-task/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Moskvin23/test-task/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/test-task/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/test-task/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/test-task/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/test-task/deployments',
    created_at: '2023-02-01T14:09:03Z',
    updated_at: '2023-02-01T14:13:49Z',
    pushed_at: '2023-02-01T14:53:10Z',
    git_url: 'git://github.com/Moskvin23/test-task.git',
    ssh_url: 'git@github.com:Moskvin23/test-task.git',
    clone_url: 'https://github.com/Moskvin23/test-task.git',
    svn_url: 'https://github.com/Moskvin23/test-task',
    homepage: null,
    size: 477,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
  },
  {
    id: 434268357,
    node_id: 'R_kgDOGeJoxQ',
    name: 'test-task-Werdevs',
    full_name: 'Moskvin23/test-task-Werdevs',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/test-task-Werdevs',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs',
    forks_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/test-task-Werdevs/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/hooks',
    issue_events_url:
      'https://api.github.com/repos/Moskvin23/test-task-Werdevs/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/events',
    assignees_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/stargazers',
    contributors_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/subscribers',
    subscription_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Moskvin23/test-task-Werdevs/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/merges',
    archive_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/test-task-Werdevs/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/test-task-Werdevs/deployments',
    created_at: '2021-12-02T15:10:15Z',
    updated_at: '2021-12-02T17:09:55Z',
    pushed_at: '2021-12-02T17:09:52Z',
    git_url: 'git://github.com/Moskvin23/test-task-Werdevs.git',
    ssh_url: 'git@github.com:Moskvin23/test-task-Werdevs.git',
    clone_url: 'https://github.com/Moskvin23/test-task-Werdevs.git',
    svn_url: 'https://github.com/Moskvin23/test-task-Werdevs',
    homepage: null,
    size: 1565,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
  },
  {
    id: 568954615,
    node_id: 'R_kgDOIemO9w',
    name: 'testTaskForJuniorPosition',
    full_name: 'Moskvin23/testTaskForJuniorPosition',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/testTaskForJuniorPosition',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition',
    forks_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/hooks',
    issue_events_url:
      'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/events',
    assignees_url:
      'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/assignees{/user}',
    branches_url:
      'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/stargazers',
    contributors_url:
      'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/subscribers',
    subscription_url:
      'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/commits{/sha}',
    git_commits_url:
      'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/git/commits{/sha}',
    comments_url:
      'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/issues/comments{/number}',
    contents_url:
      'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/contents/{+path}',
    compare_url:
      'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/merges',
    archive_url:
      'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/pulls{/number}',
    milestones_url:
      'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/testTaskForJuniorPosition/deployments',
    created_at: '2022-11-21T19:13:42Z',
    updated_at: '2022-11-21T19:26:16Z',
    pushed_at: '2022-11-21T19:47:50Z',
    git_url: 'git://github.com/Moskvin23/testTaskForJuniorPosition.git',
    ssh_url: 'git@github.com:Moskvin23/testTaskForJuniorPosition.git',
    clone_url: 'https://github.com/Moskvin23/testTaskForJuniorPosition.git',
    svn_url: 'https://github.com/Moskvin23/testTaskForJuniorPosition',
    homepage: null,
    size: 7425,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
  },
  {
    id: 366180890,
    node_id: 'MDEwOlJlcG9zaXRvcnkzNjYxODA4OTA=',
    name: 'ToDo-List',
    full_name: 'Moskvin23/ToDo-List',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/ToDo-List',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/ToDo-List',
    forks_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/ToDo-List/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/hooks',
    issue_events_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/events',
    assignees_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/stargazers',
    contributors_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/subscribers',
    subscription_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/merges',
    archive_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/ToDo-List/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/ToDo-List/deployments',
    created_at: '2021-05-10T21:32:39Z',
    updated_at: '2021-05-30T17:56:13Z',
    pushed_at: '2021-05-30T17:56:11Z',
    git_url: 'git://github.com/Moskvin23/ToDo-List.git',
    ssh_url: 'git@github.com:Moskvin23/ToDo-List.git',
    clone_url: 'https://github.com/Moskvin23/ToDo-List.git',
    svn_url: 'https://github.com/Moskvin23/ToDo-List',
    homepage: null,
    size: 4,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
  },
  {
    id: 434972979,
    node_id: 'R_kgDOGe0pMw',
    name: 'Weather-app',
    full_name: 'Moskvin23/Weather-app',
    private: false,
    owner: {
      login: 'Moskvin23',
      id: 79521676,
      node_id: 'MDQ6VXNlcjc5NTIxNjc2',
      avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Moskvin23',
      html_url: 'https://github.com/Moskvin23',
      followers_url: 'https://api.github.com/users/Moskvin23/followers',
      following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
      gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
      organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
      repos_url: 'https://api.github.com/users/Moskvin23/repos',
      events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Moskvin23/Weather-app',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Moskvin23/Weather-app',
    forks_url: 'https://api.github.com/repos/Moskvin23/Weather-app/forks',
    keys_url: 'https://api.github.com/repos/Moskvin23/Weather-app/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Moskvin23/Weather-app/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Moskvin23/Weather-app/teams',
    hooks_url: 'https://api.github.com/repos/Moskvin23/Weather-app/hooks',
    issue_events_url: 'https://api.github.com/repos/Moskvin23/Weather-app/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Moskvin23/Weather-app/events',
    assignees_url: 'https://api.github.com/repos/Moskvin23/Weather-app/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Moskvin23/Weather-app/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Moskvin23/Weather-app/tags',
    blobs_url: 'https://api.github.com/repos/Moskvin23/Weather-app/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Moskvin23/Weather-app/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Moskvin23/Weather-app/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Moskvin23/Weather-app/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Moskvin23/Weather-app/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Moskvin23/Weather-app/languages',
    stargazers_url: 'https://api.github.com/repos/Moskvin23/Weather-app/stargazers',
    contributors_url: 'https://api.github.com/repos/Moskvin23/Weather-app/contributors',
    subscribers_url: 'https://api.github.com/repos/Moskvin23/Weather-app/subscribers',
    subscription_url: 'https://api.github.com/repos/Moskvin23/Weather-app/subscription',
    commits_url: 'https://api.github.com/repos/Moskvin23/Weather-app/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Moskvin23/Weather-app/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Moskvin23/Weather-app/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/Moskvin23/Weather-app/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Moskvin23/Weather-app/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Moskvin23/Weather-app/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Moskvin23/Weather-app/merges',
    archive_url: 'https://api.github.com/repos/Moskvin23/Weather-app/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Moskvin23/Weather-app/downloads',
    issues_url: 'https://api.github.com/repos/Moskvin23/Weather-app/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Moskvin23/Weather-app/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Moskvin23/Weather-app/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Moskvin23/Weather-app/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Moskvin23/Weather-app/labels{/name}',
    releases_url: 'https://api.github.com/repos/Moskvin23/Weather-app/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Moskvin23/Weather-app/deployments',
    created_at: '2021-12-04T18:01:38Z',
    updated_at: '2021-12-04T21:07:13Z',
    pushed_at: '2021-12-04T21:07:10Z',
    git_url: 'git://github.com/Moskvin23/Weather-app.git',
    ssh_url: 'git@github.com:Moskvin23/Weather-app.git',
    clone_url: 'https://github.com/Moskvin23/Weather-app.git',
    svn_url: 'https://github.com/Moskvin23/Weather-app',
    homepage: null,
    size: 224,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'HTML',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
  },
];
