export default {
  login: 'Moskvin23',
  id: 79521676,
  node_id: 'MDQ6VXNlcjc5NTIxNjc2',
  avatar_url: 'https://avatars.githubusercontent.com/u/79521676?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Moskvin23',
  html_url: 'https://github.com/Moskvin23',
  followers_url: 'https://api.github.com/users/Moskvin23/followers',
  following_url: 'https://api.github.com/users/Moskvin23/following{/other_user}',
  gists_url: 'https://api.github.com/users/Moskvin23/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/Moskvin23/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Moskvin23/subscriptions',
  organizations_url: 'https://api.github.com/users/Moskvin23/orgs',
  repos_url: 'https://api.github.com/users/Moskvin23/repos',
  events_url: 'https://api.github.com/users/Moskvin23/events{/privacy}',
  received_events_url: 'https://api.github.com/users/Moskvin23/received_events',
  type: 'User',
  site_admin: false,
  name: 'Moskvin Pavlo',
  company: 'Azon5',
  blog: '',
  location: 'Lviv , Ukraine',
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 17,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2021-02-23T13:23:55Z',
  updated_at: '2023-02-01T14:00:12Z',
};
